name: Complexity Check

on: pull_request

jobs:
  complexity:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write


    steps:

      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Check project complexity
        uses: paiml/pmat-action@main
        with:
          max-cyclomatic: 10
          fail-on-violation: true
          comment-on-pr: true
